@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":PersonDeleteCommandParser" as PersonDeleteCommandParser LOGIC_COLOR
participant "d:PersonDeleteCommand" as PersonDeleteCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("deletep 1")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("deletep 1")
activate AddressBookParser

create PersonDeleteCommandParser
AddressBookParser -> PersonDeleteCommandParser
activate PersonDeleteCommandParser

PersonDeleteCommandParser --> AddressBookParser
deactivate PersonDeleteCommandParser

AddressBookParser -> PersonDeleteCommandParser : parse("1")
activate PersonDeleteCommandParser

create PersonDeleteCommand
PersonDeleteCommandParser -> PersonDeleteCommand
activate PersonDeleteCommand

PersonDeleteCommand --> PersonDeleteCommandParser : d
deactivate PersonDeleteCommand

PersonDeleteCommandParser --> AddressBookParser : d
deactivate PersonDeleteCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
PersonDeleteCommandParser -[hidden]-> AddressBookParser
destroy PersonDeleteCommandParser

AddressBookParser --> LogicManager : d
deactivate AddressBookParser

LogicManager -> PersonDeleteCommand : execute()
activate PersonDeleteCommand

PersonDeleteCommand -> Model : deletePerson(1)
activate Model

Model --> PersonDeleteCommand
deactivate Model

create CommandResult
PersonDeleteCommand -> CommandResult
activate CommandResult

CommandResult --> PersonDeleteCommand
deactivate CommandResult

PersonDeleteCommand --> LogicManager : result
deactivate PersonDeleteCommand

[<--LogicManager
deactivate LogicManager
@enduml
